CREATE TABLE "users"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "auth_type"     VARCHAR,
    "email"         VARCHAR     NOT NULL,
    "name"          VARCHAR     NOT NULL,
    "profile_image" VARCHAR,
    "kakao_user_id" VARCHAR,
    "created_at"    TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'Asia/Seoul'),
    "updated_at"    TIMESTAMPTZ,
    "deleted_at"    TIMESTAMPTZ
);

CREATE INDEX "idx_users_deleted_at" ON "users" ("deleted_at");

COMMENT ON COLUMN "users"."kakao_user_id" IS '카카오 회원번호';
