server:
  env: local
  port: 8080
  readTimeout: 10 # second
  writeTimeout: 10 # second

database:
  host: localhost
  port: '5432'
  dbname: postgres
  user: postgres
  password: '1025'
  timezone: Asia/Seoul
