create table users (
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    email      varchar(50) not null,
    password   varchar(50) not null,
    created_at timestamp   not null default now() as timezone 'Asia/Seoul',
    updated_at timestamp,
    deleted_at timestamp
);

-- index
create index idx_item_deleted_at on users(deleted_at);